# Generated by Django 4.0.2 on 2022-02-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='pf_image',
            field=models.ImageField(default='static/profiles/default_img', upload_to='pf_image'),
        ),
    ]
