# Generated by Django 4.0.1 on 2022-01-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikes',
            name='postId',
            field=models.ForeignKey(db_column='postId', on_delete=django.db.models.deletion.CASCADE, to='contents.postmodel'),
        ),
    ]
