# Generated by Django 4.0.1 on 2022-01-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userlikes_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlikes',
            old_name='postId',
            new_name='post_id',
        ),
    ]
