# Generated by Django 4.0.2 on 2022-02-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('post_title', models.CharField(max_length=200)),
                ('post_category', models.CharField(max_length=200)),
                ('like_count', models.IntegerField()),
                ('post_file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('post_thumbnail', models.URLField()),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
