# Generated by Django 4.0 on 2022-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_url', models.CharField(default='', max_length=200, null=True)),
                ('post_category', models.CharField(max_length=200)),
                ('like_count', models.IntegerField(null=True)),
                ('post_file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('post_thumbnail', models.URLField()),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='RecommendModel',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False)),
                ('re_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recommend',
            },
        ),
    ]
